//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Assets {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUI.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add files.
        /// </summary>
        public static string Add_files {
            get {
                return ResourceManager.GetString("Add files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ask.
        /// </summary>
        public static string Ask {
            get {
                return ResourceManager.GetString("Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear only converted files.
        /// </summary>
        public static string Clear_converted_files {
            get {
                return ResourceManager.GetString("Clear converted files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear list.
        /// </summary>
        public static string Clear_list {
            get {
                return ResourceManager.GetString("Clear list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy attributes and dates from original files.
        /// </summary>
        public static string Copy_attributes {
            get {
                return ResourceManager.GetString("Copy attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successfully converted.
        /// </summary>
        public static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete original files when conversion finishes.
        /// </summary>
        public static string Delete_original_files {
            get {
                return ResourceManager.GetString("Delete original files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use the &quot;Add files&quot; button below or drag and drop files here.
        /// </summary>
        public static string Drag_and_drop_message {
            get {
                return ResourceManager.GetString("Drag and drop message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your selection has GIF files. Only the first frame can be converted to QOI. Do you want to remove those GIF files from your selection?.
        /// </summary>
        public static string GIF_files_confirmation {
            get {
                return ResourceManager.GetString("GIF files confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum value is taken from the processor count of your computer.
        /// </summary>
        public static string Max_value_parallel_processes {
            get {
                return ResourceManager.GetString("Max value parallel processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press &quot;Start conversion&quot; to initiate operations.
        /// </summary>
        public static string Null_operation {
            get {
                return ResourceManager.GetString("Null operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of parallel processes.
        /// </summary>
        public static string Number_of_parallel_processes {
            get {
                return ResourceManager.GetString("Number of parallel processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Overwrite.
        /// </summary>
        public static string Overwrite {
            get {
                return ResourceManager.GetString("Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start conversion.
        /// </summary>
        public static string Start_conversion {
            get {
                return ResourceManager.GetString("Start conversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Initiate conversion immediately when you add files to the list.
        /// </summary>
        public static string Start_immediately {
            get {
                return ResourceManager.GetString("Start immediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waiting other images to finish to start conversion.
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a What to do with files with the same name?.
        /// </summary>
        public static string What_to_do_with_same_name_files {
            get {
                return ResourceManager.GetString("What to do with same name files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Converting image....
        /// </summary>
        public static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
